/* automatically generated by rust-bindgen 0.59.2 */

pub const KYBER_K: u32 = 3;
pub const KYBER_N: u32 = 256;
pub const KYBER_Q: u32 = 7681;
pub const KYBER_ETA: u32 = 4;
pub const KYBER_SYMBYTES: u32 = 32;
pub const KYBER_POLYBYTES: u32 = 416;
pub const KYBER_POLYCOMPRESSEDBYTES: u32 = 96;
pub const KYBER_POLYVECBYTES: u32 = 1248;
pub const KYBER_POLYVECCOMPRESSEDBYTES: u32 = 1056;
pub const KYBER_INDCPA_MSGBYTES: u32 = 32;
pub const KYBER_INDCPA_PUBLICKEYBYTES: u32 = 1088;
pub const KYBER_INDCPA_SECRETKEYBYTES: u32 = 1248;
pub const KYBER_INDCPA_BYTES: u32 = 1152;
pub const KYBER_PUBLICKEYBYTES: u32 = 1088;
pub const KYBER_SECRETKEYBYTES: u32 = 2400;
pub const KYBER_CIPHERTEXTBYTES: u32 = 1152;
extern "C" {
    pub fn crypto_kem_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn crypto_kem_enc(
        ct: *mut ::std::os::raw::c_uchar,
        ss: *mut ::std::os::raw::c_uchar,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[must_use]
    pub fn crypto_kem_dec(
        ss: *mut ::std::os::raw::c_uchar,
        ct: *const ::std::os::raw::c_uchar,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
